import { Roboto } from '@next/font/google';
import { Suspense } from 'react';
import Loading from './loading';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <Suspense fallback={<Loading />}>
        <body className={roboto.className}>{children}</body>
      </Suspense>
    </html>
  );
}
