import { Header } from '@/components/header';
import { globalStyles } from '@/styles/global';
import { Container } from '@/styles/pages/app';
import { Roboto } from '@next/font/google';
import { getCssText } from '../styles';
export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

globalStyles();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={roboto.className}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
